# Generated by Django 3.2.5 on 2022-12-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App01', '0002_auto_20221208_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrettyNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, verbose_name='手机号')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('level', models.SmallIntegerField(choices=[(1, '1级'), (1, '1级'), (1, '1级'), (1, '1级')], default=1, verbose_name='级别')),
                ('status', models.SmallIntegerField(choices=[(0, '已占用'), (1, '未占用')], default=1, verbose_name='状态')),
            ],
        ),
    ]
