# Generated by Django 3.2.5 on 2022-12-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App01', '0003_prettynumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prettynumber',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '1级'), (2, '2级'), (3, '3级'), (4, '4级')], default=1, verbose_name='级别'),
        ),
    ]
