# Generated by Django 3.2.5 on 2022-12-25 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App01', '0005_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='任务')),
                ('detail', models.CharField(max_length=64, verbose_name='详细信息')),
                ('level', models.SmallIntegerField(choices=[(1, '紧急'), (2, '重要'), (3, '临时')], default=1, verbose_name='基本')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App01.admin', verbose_name='负责人')),
            ],
        ),
    ]
